config/routes.rb
Rails.application.routes.draw do

  root to: "static_pages#index"
  resource :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chirp.rb
class Chirp < ApplicationRecord
  belongs_to :user, class_name: "User", foreign_key: "user_id"
end

app/models/user.rb
class User < ApplicationRecord
  has_many :chimps, class_name: "Chirp"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create

  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
    @chirps = Chirp.all
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBirds</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class="navbar navbar-default">
      <div class="collapse navbar-collapse">
        <a class="navbar-brand"> Brand </a>
          <ul class="nav navbar-nav navbar-right">
            <li> <a href="#">Sing In</a></li>
            <li> <a href="<%= new_users_path %>">Sing Up</a> </li>
          </ul>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/static_pages/index.html.erb
<h1 class="text-center">Welcome to the Bird's App</h1>
<div class="container">
  <section class="chirps">
    <% @chirps.each do |ch| %>
    <article class="chirp">
      <ul>
        <li>
          <%= ch.user.first_name %>
        </li>
      </ul>
      <%= ch.body %>
    </article>
    <% end %>
  </section>
</div>

app/views/users/new.html.erb
<div class="container">

  <%= form_for @user do |f| %>

  <div class="form-group">
    <label for="user_nickname">Nickname</label>
    <input type="text" name="user[nickname]" id="user_nickname" class="form-control">
  </div>

  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <label for="user_last_name">Last name</label>
    <input type="text" name="user[last_name]" value="<%= @user.last_name %>" id="user_last_name" class="form-control">
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <label for="user_password">Password</label>
    <input type="Password" name="user[password]" id="user_password" class="form-control">
  </div>

  <div class="form-group">
    <label for="user_password">Password Confirmation</label>
    <input type="password" name="user[password_confirmation]" id="user_password_confirmation" class="form-control">
  </div>

  <% end %>
</div>